config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :car_offers, only: [ :index, :create, :new, :show ] do
    resources :rents, only: :create
  end

  get "/dashboard", to: "dashboard#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car_offer.rb
class CarOffer < ApplicationRecord
  belongs_to :user
  has_many :rents
  # include AlgoliaSearch

  # algoliasearch do
  #   attribute :first_name, :last_name, :email
  # end

  mount_uploader :photo, PhotoUploader

  validates :brand, presence: true, allow_blank: false, allow_nil: false
  validates :model, presence: true, allow_blank: false, allow_nil: false
  validates :title, presence: true, allow_blank: false, allow_nil: false
  validates :horsepower, presence: true, allow_blank: false, allow_nil: false
  validates :price, presence: true, allow_blank: false, allow_nil: false
  validates :description, presence: true, allow_blank: false, allow_nil: false
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :car_offer
  belongs_to :user
end

app/models/renter.rb
class Renter < ApplicationRecord
  belongs_to :user
  validates :last_name, presence: true, allow_blank: false, allow_nil: false
  validates :first_name, presence: true, allow_blank: false, allow_nil: false
  validates :user, presence: true, allow_blank: false, allow_nil: false
end

app/models/seller.rb
class Seller < ApplicationRecord
  belongs_to :user
  has_many :car_offers
  has_many :rents, through: :car_offers
  validates :last_name, presence: true, allow_blank: false, allow_nil: false
  validates :first_name, presence: true, allow_blank: false, allow_nil: false
  validates :user, presence: true, allow_blank: false, allow_nil: false
end

app/models/user.rb
class User < ApplicationRecord
  # has_one :seller
  # has_one :renter
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, uniqueness: true, presence: true, allow_nil: false, allow_blank: false
  has_many :rents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/car_offers_controller.rb
class CarOffersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    @car_offers = CarOffer.all
  end

  def show
    @car_offer = CarOffer.find(params[:id])
    @rent = Rent.new
  end

  def new
    @car_offer = CarOffer.new
  end

  def create
    @car_offer = CarOffer.new(car_offer_params)
    @car_offer.user = current_user
    if @car_offer.save
      redirect_to car_offers_path
    else
      render "new"
    end
  end

  private

  def car_offer_params
    params.require(:car_offer).permit(:title, :brand, :model, :description, :price, :horsepower, :photo, :photo_cache)
  end
end

 # if user.seller == true
 #      @car_offer = user.seller.id
 #    else
 #      a = Seller.new
 #    end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    @user = current_user
    @rents = @user.rents
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!
  def home
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  def create
    @rent = Rent.new(rent_params)
    @car_offer = CarOffer.find(params[:car_offer_id])
    @rent.car_offer = @car_offer
    @rent.price_total = @rent.car_offer.price

    if @rent.car_offer.price * ((@rent.end_date - @rent.start_date) / 86_400) < @rent.car_offer.price
      @rent.price_total = @rent.car_offer.price
    else
      @rent.price_total = @rent.car_offer.price * ((@rent.end_date - @rent.start_date) / 86_400)
    end


    @rent.user = current_user

    if @rent.save
      redirect_to car_offers_path
    else
      render "car_offers/show"
    end
  end

  private

  def rent_params
    params.require(:rent).permit(:start_date, :end_date)
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController

  def new
    @car_offers = CarOffers.new
  end

  def create
    @car_offers = CarOffers.new(car_offers_params)
    if @car_offers.save
      redirect_to car_offers_path(@car_offers)
    else
      redirect_to car_offers_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/car_offers/brand_index.html.erb
<% @cars.where(brand: params[:brand]).each do |car| %>
  <%= car.title %> <br>
<% end %>

app/views/car_offers/index.html.erb
<%= render 'shared/navbar2' %>
<div class="container">
    <div class="row">
    <% @car_offers.each do |car| %>
        <div class="col-12 col-sm-6 col-md-4">
      <%= link_to car_offer_path(car) do %>
          <div class="card my-3">
            <%= cl_image_tag("#{car.photo.url}", class: "card-img-top") %>
              <%= link_to "#{car.brand} #{car.model} - #{car.title}", car_offer_path(car), class: "px-4 py-3" %>
          </div>
        <% end %>
        </div>
      <% end %>
    </div>
</div>

app/views/car_offers/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
  url(<%= image_url("https://www.pixelstalk.net/wp-content/uploads/2016/06/Free-Download-HD-Car-Wallpapers.jpg") %>);width:100vw; height:100vh; background-repeat: no-repeat; background-position: center;
  background-size: cover;">
  <div>
    <div class="create-new-car-form" style="width:50vh;">
      <%= simple_form_for(@car_offer)  do |f| %>
        <%= f.input :title %>
        <%= f.input :brand, collection: ['Bugatti', 'Ferrari', 'Lamborghini', 'McLaren',  'Porsche',  'Tesla'] %>
        <%= f.input :model %>
        <%= f.input :horsepower %>
        <%= f.input :price %>
        <%= f.input :description %>
        <%= f.input :photo, class: "btn btn-flat btn-info" %>
        <%= f.input :photo_cache, as: :hidden %>
        <%= f.submit "Add Car to the fleet", class: "btn btn-flat btn-info" %>
      <% end  %>
    </div>
    <div class="container">
      <div class="mx-auto text-center mt-5">
        <%= link_to car_offers_path, class: "btn-flat btn btn-outline-info" do %>
          <p class="flex-item-center-margin">Go back to list</p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/car_offers/show.html.erb
<%= render 'shared/navbar2' %>
<div class="container-fluid delete-navbar-margin">
  <div class="row">
    <div class="card-category card-show">
      <%= @car_offer.brand %>
      <%= @car_offer.model  %>
    </div>
    <div class="banner-image-cars" style='background-image: url(<%= cl_image_path @car_offer.photo, crop: :fill; %>)'></div>
  </div>
</div>
<div class="container">
  <h3 class="mt-5"><%= @car_offer.title %></h3>
  <div class="row">
    <p><%= @car_offer.description %></p>
  </div>
  <hr>
  <div class="d-flex justify-content-between mt-5 align-items-center">
    <p class="flex-item-center-margin">
      <%= "Horsepower: #{@car_offer.horsepower}"  %>
    </p>
    <%= link_to "#{@car_offer.price} € a day", "#car", class: "btn btn-info btn-flat" %>
  </div>
</div>
<div>
      <div class="create-new-car-form" id="car" style="width:50vh;">
        <%= simple_form_for([@car_offer, @rent])  do |f| %>
          <%= f.input :start_date%>
          <%= f.input :end_date %>
          <%= f.submit "Rent this car for €#{@car_offer.price} a day", class: "btn btn-info btn-flat" %>
         <%= link_to root_path do %>
      <% end %>
      <% end  %>
    </div>
  </div>
<div class="move-page-up"></div>

app/views/dashboard/show.html.erb
<%= render 'shared/navbar2' %>
<div class="container">
  <h3 style="font-weight: 200" class="mx-auto my-3 text-center">Your bookings:</h3>
  <div id='test_div' class="row">
    <% @rents.each do |rent| %>
    <!-- <div class="container-fluid "> -->
      <div class="col-12 col-sm-6">
        <div class="card card2 py-3">
          <p> Car:
            <%= link_to "#{rent.car_offer.brand} #{rent.car_offer.model}", car_offer_path(rent.car_offer)  %>
          </p>
          <p> From: <%= rent.start_date %></p>
          <p> Till: <%= rent.end_date %></p>
          <p> Total Price for the rent: €<%= rent.price_total %></p>
        </div>
      </div>
    <!-- </div> -->
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, user-scalable=no">
    <title>LUXCAR</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" defer="true"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" defer="true"></script>

    <%= javascript_include_tag 'application', defer: true %>
    <%= javascript_pack_tag 'application', defer: true %>
  </head>
  <body>
    <!-- alert regarding sign up form -->
    <% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/_post_home.html.erb
<%= render 'shared/navbar' %>

<!-- NAVBAR HERE NOT ON THE APPLICATION HTML ERB
      CAROUSEL
      TEXT
 -->
<div class="container" style="margin-top: 50px; margin-bottom: 50px;">
  <div style="text-align: center;">
    <p>Wanna pull up in a sick whip that you can’t afford,
in order to impress people that you don’t know so you can push your
self-esteem ?</p>
<p>No problem we gotcha !</p>
<p>We got the perfect car for every scenario:</p>
<p>An unforgettable ride towards the sunset with your girl and the sound of 700 horses when you hit the gas?</p>
<p>No problem, the Lambo’s just fine for that.</p>
<p>Or maybe you just wanna pose and catch the views of underage teenagers, while being stuck in city traffic, with a car that needs 35L of gasoline?</p>
<p>Easy the Bugatti is the perfect fit if you wanna go 30 in the city with a 1000hp engine.</p>
<p>Got a headache because last night was to wild and you have to show up to brunch with your girlfriends family ?</p>
<p>We’ve all been there.</p>
<p>And because we can relate to that we even offer you the newest Tesla models.
So we can spare you from the headache on your way to brunch.</p>
<p>So what ever you need we got you covered.</p>
<h4>Your Lux Team</h4>
  </div>
</div>

app/views/pages/home.html.erb
<div class="headers-landing-page">
  <div class="banner d-flex flex-column justify-content-center align-items-center" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),url('<%= cl_image_path("gabriel-gurrola-125352-unsplash.jpg", :height=>900, :crop=>"fit") %>');width:100vw; height:100vh; background-repeat: no-repeat; background-position: center;
         background-size: cover;">
    <div class="d-flex flex-column h-100 align-items-center" style="padding-top: 159px;">
      <h1 class="pt-5 headline" style="color: rgba(255,255,255,0.7);">Rent a <strong>special car</strong> via <strong>LUXCAR</strong>!</h1>
      <%= link_to "Take a look",car_offers_path, class:"btn btn-info home-cta" %>
    </div>
    <div class="arrow">
      <%= image_tag "Arrowdown.png" %>
    </div>
  </div>

 <%= render 'post_home' %>


 <div id="carouselExampleInterval" class="carousel slide" data-ride="carousel" style="background-color:aliceblue">
   <div class="carousel-inner" style="margin-bottom: 60px; margin-top: 60px;">
     <div class="carousel-item active" data-interval="2000">
       <div class="d-flex flex-row justify-content-between">
         <div>
            <%= link_to car_offers_path do %>
              <%= image_tag "Porsche.png", width: 500, height: 300 %>
            <% end %>
         </div>
         <div>
            <%= link_to car_offers_path do %>
           <%= image_tag "Lambo.png", width: 250, height: 300 %>
            <% end %>
         </div>
         <div>
            <%= link_to car_offers_path do %>
           <%= image_tag "Ferrari.png", width: 500, height: 300 %>
            <% end %>
         </div>
       </div>
     </div>
     <div class="carousel-item" data-interval="2000">
     <div class="d-flex flex-row justify-content-between">
      <div>
          <%= link_to car_offers_path do %>
        <%= image_tag "Bugatti.png", width: 400, height: 250 %>
         <% end %>
      </div>
      <div>
          <%= link_to car_offers_path do %>
        <%= image_tag "Tesla.png", width: 250, height: 300 %>
         <% end %>
      </div>
      <div>
          <%= link_to car_offers_path do %>
        <%= image_tag "McLaren.png", width: 450, height: 300 %>
         <% end %>
      </div>
     </div>
   </div>
 </div>
   <a class="carousel-control-prev" href="#carouselExampleInterval" role="button" data-slide="prev">
     <span class="carousel-control-prev-icon" aria-hidden="true"></span>
     <span class="sr-only">Previous</span>
   </a>
   <a class="carousel-control-next" href="#carouselExampleInterval" role="button" data-slide="next">
     <span class="carousel-control-next-icon" aria-hidden="true"></span>
     <span class="sr-only">Next</span>
   </a>
 </div>

app/views/rents/show.html.erb
<h1>HI</h1>

app/views/shared/_navbar.html.erb
<!-- LOOK AT FIGMA -->

<div class="navbar-wagon navbar fixed-top d-none">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <p class="flex-item-center-margin navbar-logo">LUXCAR</p>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right d-none d-md-flex">
    <% if user_signed_in? %>
    <!-- Links when logged in -->
    <%= link_to "Host a car", new_car_offer_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Rides", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <form class="form-inline active-cyan-4">
      <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
      <i class="fas fa-search" aria-hidden="true"></i>
    </form>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
            <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <form class="form-inline active-cyan-4">
      <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
      <i class="fas fa-search" aria-hidden="true"></i>
    </form>s
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item d-inline d-md-none">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>
</div>

</div>
</div>

app/views/shared/_navbar2.html.erb
<div class="navbar-lewagon navbar fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <p class="flex-item-center-margin navbar-logo">LUXCAR</p>
  <% end %>
  <!-- Right Navigation -->
  <div class="navbar-wagon-right d-none d-md-flex">
    <% if user_signed_in? %>
    <!-- Links when logged in -->
    <%= link_to "Host a car", new_car_offer_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Rides", dashboard_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <form class="form-inline active-cyan-4">
      <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
      <i class="fas fa-search" aria-hidden="true"></i>
    </form>
    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <i class="fas fa-bars dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown"></i>
        <!-- , class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" -->
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <% else %>
    <!-- Login link (when logged out) -->
    <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <form class="form-inline active-cyan-4">
      <input class="form-control form-control-sm mr-3 w-75" type="text" placeholder="Search" aria-label="Search">
      <i class="fas fa-search" aria-hidden="true"></i>
    </form>s
    <% end %>
  </div>
  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item d-inline d-md-none">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>
<div class="navbar-fixed-hide">

</div>

app/views/shared/footer.html.erb
<!-- footer like on AIR BNB -->